name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Install dependencies
        run: go get .

      - name: Build for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -v -o healthchecker-linux-amd64 ./...

      - name: Build for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -v -o healthchecker-linux-arm64 ./...

      - name: Build for Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -v -o healthchecker-windows-amd64 ./...

      - name: Build for Windows arm64
        run: GOOS=windows GOARCH=arm64 go build -v -o healthchecker-windows-arm64 ./...

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Generate Tag Name
        id: tag_name
        run: echo "v$(date +'%Y%m%d%H%M%S')" >> tag_name.txt

      - name: Create Tag
        run: git tag $(cat tag_name.txt)

      - name: Github Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag_name.outputs.stdout }}
          files: ./healthchecker-*